server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: http://usuario-service.railway.internal:8081
          predicates:
            - Path=/usuarios/**

        - id: producto-service
          uri: http://producto-service.railway.internal:8082
          predicates:
            - Path=/productos/**

        - id: pedido-service
          uri: http://pedido-service.railway.internal:8083
          predicates:
            - Path=/pedidos/**

        - id: carrito-service
          uri: http://carrito-service.railway.internal:8084
          predicates:
            - Path=/carritos/**