server:
  port: 8081

spring:
  application:
    name: usuario-service
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&serverTimezone=UTC
    username: root
    password: isPtxkpfTWzPFOFQDfkFFuVTdLXHPsmm
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true