server:
  port: 8083

spring:
  application:
    name: pedido-service
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&serverTimezone=UTC
    username: root
    password: isPtxkpfTWzPFOFQDfkFFuVTdLXHPsmm
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: https://shimmering-amazement-production-39a5.up.railway.app/eureka/