server:
  port: 8083

spring:
  application:
    name: pedido-service
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE:onlineshop}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

producto-service:
  url: ${PRODUCTO_SERVICE_URL:https://producto-service-production-a90b.up.railway.app}

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}