server:
  port: 8084

spring:
  application:
    name: carrito-service
  datasource:
    url: jdbc:mysql://localhost:3306/onlineshop?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: [https://shimmering-amazement-production-39a5.up.railway.app/eureka/](https://shimmering-amazement-production-39a5.up.railway.app/eureka/)